name: 拉取提交
on:
  workflow_dispatch:
    inputs:
      commit-hash: { description: "目标提交的哈希值" }
      target-repo: { description: "目标仓库的URL" }
      target-branch: { description: "目标仓库的分支名称", default: "main" }

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          echo "commit-hash=${{ github.event.inputs.commit-hash }}" >> $GITHUB_ENV
          echo "target-repo=${{ github.event.inputs.target-repo }}" >> $GITHUB_ENV
          echo "target-branch=${{ github.event.inputs.target-branch }}" >> $GITHUB_ENV

      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Add remote repository
        run: git remote add other-repo "${{ github.event.inputs.target-repo }}.git"  # 保持短横线命名

      - name: Fetch the target commit
        run: git fetch other-repo "${{ github.event.inputs.target-branch }}"  # 保持短横线命名

      - name: Cherry-pick the commit
        run: git cherry-pick "${{ github.event.inputs.commit-hash }}"
